services:
  backend:
    build:
      context: .
      dockerfile: dotnet/QR-Code-generator/Dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "3000:3000"
